CREATE TABLE IF NOT EXISTS `deHasher_md5` (
  `Hash` varchar(128) NOT NULL DEFAULT '',
  `Text` varchar(2048) NOT NULL DEFAULT ''
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `deHasher_md5_md5` (
  `Hash` varchar(128) NOT NULL DEFAULT '',
  `Text` varchar(2048) NOT NULL DEFAULT ''
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `deHasher_sha1` (
  `Hash` varchar(128) NOT NULL DEFAULT '',
  `Text` varchar(2048) NOT NULL DEFAULT ''
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
